name: Deploy NestJS with Prisma and Redis to VPS using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist!"
            mkdir -p /home/ubuntu/fixoo
            cd /home/ubuntu/fixoo

            if [ ! -d "edora_backend/.git" ]; then
              echo "Cloning repository!" 
              git clone https://github.com/tuxtasinboyev/edora_backend.git
            else
              echo "Pulling latest changes!"
              cd edora_backend    
              git pull origin main  
            fi
  
            echo "Stopping containers"
            docker-compose down

            echo "Building containers"
            docker-compose build 

            echo "Running containers"
            docker-compose up -d
