name: 🚀 Auto Deploy to Ubuntu via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🔧 Deploy edora_backend to Server
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          debug: true
          script: |
            echo "👉 Loyihani yuklab olish yoki yangilash..."
            cd /root

            if [ -d "edora_backend" ]; then
              cd edora_backend
              git reset --hard
              git clean -fd
              git pull origin main
            else
              git clone https://github.com/tuxtasinboyev/edora_backend.git
              cd edora_backend
            fi

            echo "🧼 Eski containerlarni to‘xtatish..."
            docker compose down || true

            echo "📦 Docker build va up..."
            docker compose up -d --build

            echo "✅ Deploy yakunlandi!"

            