name: 🚀 Auto Deploy to Ubuntu via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist!"
            mkdir -p /home/ubuntu/fixoo
            cd /home/ubuntu/fixoo

            if [ -d "edora_backend" ]; then
              echo "Cloning repository!" 
                 git clone https://${{ secrets.GH_TOKEN }}@github.com/tuxtasinboyev/edora_backend.git
              cd edora_backend
            else
              echo "Pulling latest changes!"
              cd edora_backend
              git pull origin main
            fi
  
            echo "Stopping containers"
            docker compose down

            echo "Building containers"
            docker compose build 

            echo "Running containers"
            docker compose up -d
